In [1]:
import numpy as np

In [2]:
# create one dimensional array
# vector as row
row_vector = np.array([1,2,3])

In [3]:
#vector as column
column_vector = np.array([[1],
                          [2],
                          [3]])

In [4]:
row_vector

array([1, 2, 3])

In [5]:
column_vector

array([[1],
       [2],
       [3]])

In [6]:
# creating matrix - should use array
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
matrix_object = np.mat([[1,2],
                       [1,2],
                       [1,2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [10]:
# create sparse matrix - store only non zero elements
from scipy import sparse
matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])
#create compressed sparse row matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# create csr matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [74]:
# selecting elements
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
vector[1]

2

In [16]:
matrix[1,1]

5

In [22]:
# Select all elements of a vector
vector[:]

# Select everything up to and including the third element
vector[:3]

# Select everything after the third element
vector[3:]

# Select the last element
vector[-1]

# Select the first two rows and all columns of a matrix
matrix[:2,:]

# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [27]:
#describe shape size dimension
print(matrix.shape)

print(matrix.size)

print(matrix.ndim)

(3, 3)
9
2


In [28]:
# apply function to multiple elements in array

#create function that adds 100 to something
add_100 = lambda i : i + 100

#create vectorized function
vectorized_add_100 = np.vectorize(add_100)

#apply function to all elements
vectorized_add_100(matrix)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [30]:
#simple way - broadcasting
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [33]:
# find the maximum or minimum value in an array
np.max(matrix)
np.min(matrix)

1

In [37]:
# Find maximum element in each column
np.max(matrix, axis=0)

# Find maximum element in each row
np.max(matrix,axis=1)

array([3, 6, 9])

In [43]:
#Calculating the Average, Variance, and Standard Deviation
np.average(matrix)
np.mean(matrix)
np.var(matrix)
np.std(matrix)

2.581988897471611

In [44]:
#  Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [48]:
#  change the shape (number of rows and columns) of an array without changing the element values.

#  shape of the original and new matrix contain the same number of elements (i.e., the same size)

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
 
#Reshape matrix into 2x6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
# One useful argument in reshape is -1, which effectively means “as many as needed,”
# so reshape(-1, 1) means one row and as many columns as needed
matrix.reshape(1,-1)

matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
# transpose a vector or matrix

# Create matrix
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
# Tranpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [55]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [58]:
 #transform a matrix into a one-dimensional array.
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# flatten is a simple method to transform a matrix into a one-dimensional array.
# Alternatively, we can use reshape to create a row vector:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
# Finding the Rank of a Matrix
# The rank of a matrix is the dimensions of the vector space spanned by its columns or
# rows. 
# Create matrix
matrix = np.array([[1, 1, 1],
                 [1, 1, 10],
                 [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [63]:
#  determinant of a matrix.
np.linalg.det(matrix)

0.0

In [76]:
#  diagonal elements of a matrix
matrix.diagonal()

array([1, 5, 9])

In [79]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([4, 8])

In [81]:
# trace of a matrix - The trace of a matrix is the sum of the diagonal elements
matrix.trace()
# or
sum(matrix.diagonal())

15

In [85]:
#find the eigenvalues and eigenvectors of a square matrix

# A, eigenvectors are vectors that, when that
# transformation is applied, change only in scale (not direction). More formally:
# Av = λv
# where A is a square matrix, λ contains the eigenvalues and v contains the eigenvec‐
# tors. In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and
# eigenvectors of any square matrix

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [87]:
# calculate the dot product of two vectors.
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a,vector_b)
vector_a @ vector_b

32

In [89]:
# add or subtract two matrices

# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])

print(np.add(matrix_a, matrix_b))
print(np.subtract(matrix_a,matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [90]:
matrix_a + matrix_b
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [95]:
#  multiply two matrices

np.dot(matrix_a,matrix_b)

matrix_a @ matrix_b

#If we want to do element-wise multiplication, we can use the * operator:
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [101]:
#  calculate the inverse of a square matrix.

# The inverse of a square matrix, A, is a second matrix A–1, such that:
# AA−1 = I
# where I is the identity matrix. In NumPy we can use linalg.inv to calculate A–1 if it
# exists. To see this in action, we can multiply a matrix by its inverse and the result is
# the identity matrix

# Create matrix
matrix = np.array([[1, 4],
                 [2, 5]])

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [102]:
# cross check
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [104]:
# generate pseudorandom values

# Finally, it can sometimes be useful to return the same random numbers multiple
# times to get predictable, repeatable results. We can do this by setting the “seed” (an
# integer) of the pseudorandom generator. Random processes with the same seed will
# always produce the same output. 

np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [108]:
# Generate three random integers between 1 and 10
np.random.randint(0,11,3)

#Alternatively, we can generate numbers by drawing them from a distribution:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0,1.0,3)

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0,3)

# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0,2.0,3)


array([1.94466892, 1.52184832, 1.41466194])